### ISSUE TITLE
Restrict merge direct to main

### ISSUE THREAD

**Issue by laysauchoa** [aiven/metadata-parser#39]
Anyone can open a pull request with changes and merge direct to the main branch. This is not safe. 

One way to fix is this by limiting merges of pull request only if it approved by at least one reviewer.

Read more here:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests

**Comment by ftisiot** [comment]
Thanks @laysauchoa done!
